docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - Introduction: v1/intro.md
site_name: 'laminas-{component}'
site_description: ''
repo_url: 'https://github.com/laminas/laminas-{component}'
extra:
    project: Components
    installation:
        config_provider_class: 'Laminas\{component}\ConfigProvider'
        module_class: 'Laminas\{component}\Module'
