docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - Introduction: v1/intro.md
site_name: 'laminas-changeme'
site_description: ''
repo_url: 'https://github.com/laminas/laminas-changeme'
extra:
    project: Components
    installation:
        config_provider_class: 'Laminas\changeme\ConfigProvider'
        module_class: 'Laminas\changeme\Module'
